const KEY='mohit_editable_v1';let S=JSON.parse(localStorage.getItem(KEY)||'{}');const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(S))}function apply(){document.body.className=(S.theme?'theme-'+S.theme:'')+' '+(S.anim&&S.anim!=='none'?'gallery-anim-'+S.anim:'')+' no-zoom';document.querySelectorAll('[data-name]').forEach(e=>e.textContent=S.name||'Mohit');document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=S.tagline||'Gamer • Creator • Student • 5x_gamerr');if(S.photo){$('#profilePhoto').src=S.photo;$('#navPhoto').src=S.photo;document.querySelectorAll('.mini-profile').forEach(e=>e.src=S.photo)}$('#aboutText').textContent=S.about||'Welcome to my personal gaming portfolio. Explore my gaming world, gallery, challenges and history.'}
window.addEventListener('load',()=>setTimeout(()=>$('#loader').style.display='none',650));$('#settingsBtn').onclick=()=>$('#settings').classList.add('open');$('.close').onclick=()=>$('#settings').classList.remove('open');$('.backdrop').onclick=()=>$('#settings').classList.remove('open');$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');alert('Dark/Light mode can be expanded from Settings themes.')};
$('#themeSelect').onchange=e=>{S.theme=e.target.value;save();apply()};$('#animSelect').onchange=e=>{S.anim=e.target.value;save();apply()};$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;if(f.size>4e6)return alert('Photo 4MB से कम रखें');let r=new FileReader();r.onload=()=>{S.photo=r.result;save();apply()};r.readAsDataURL(f)};
$('#songInput').onchange=e=>{let f=e.target.files[0];if(!f)return;if(f.size>12e6)return alert('Song 12MB से कम रखें');let r=new FileReader();r.onload=()=>{S.song=r.result;$('#audio').src=S.song;save()};r.readAsDataURL(f)};$('#songPlay').onclick=()=>$('#audio').paused?$('#audio').play():$('#audio').pause();
$('#saveProfile').onclick=()=>{S.name=$('#nameInput').value.trim();S.tagline=$('#tagInput').value.trim();S.about=$('#aboutInput').value.trim();S.email=$('#formEmail').value.trim();save();apply();setForm();alert('Profile settings saved!')};function setForm(){if(S.email)$('#formEmail').value=S.email;$('#nameInput').value=S.name||'';$('#tagInput').value=S.tagline||'';$('#aboutInput').value=S.about||'';if(S.song)$('#audio').src=S.song;$('#themeSelect').value=S.theme||'cyan';$('#animSelect').value=S.anim||'none'}
function renderW(){let a=S.winners||[];$('#winnerGrid').innerHTML=a.map((x,i)=>`<article class="winner-card"><img src="${x.img}" alt="Winner shot"><b>${esc(x.cap)}</b><br><button onclick="delW(${i})">Delete</button></article>`).join('')||'<p class="muted">No winner shots yet. Add them from Settings.</p>'}window.delW=i=>{S.winners.splice(i,1);save();renderW()};$('#addWinner').onclick=()=>{let f=$('#winnerInput').files[0],c=$('#winnerCaption').value.trim();if(!f||!c)return alert('Screenshot और caption डालें');let r=new FileReader();r.onload=()=>{S.winners=S.winners||[];S.winners.unshift({img:r.result,cap:c});save();renderW();$('#winnerInput').value='';$('#winnerCaption').value=''};r.readAsDataURL(f)};
function renderH(){let a=S.history||[];$('#historyGrid').innerHTML=a.map((x,i)=>`<article class="history-card"><b>${esc(x.game)}</b><p>UID: ${esc(x.uid)}</p><p>Username: ${esc(x.user)}</p><button onclick="delH(${i})">Delete</button></article>`).join('')||'<p class="muted">No gaming history yet.</p>'}window.delH=i=>{S.history.splice(i,1);save();renderH()};$('#addHistory').onclick=()=>{let game=$('#histGame').value.trim(),uid=$('#histUid').value.trim(),user=$('#histUser').value.trim();if(!game||!uid||!user)return alert('Game, UID और Username भरें');S.history=S.history||[];S.history.unshift({game,uid,user});save();renderH();$('#histGame').value=$('#histUid').value=$('#histUser').value=''};
$('#shareBtn').onclick=()=>share();$('#shareSettings').onclick=()=>share();async function share(){let url='https://mohitbishnoi7568-alt.github.io/';if(navigator.share){try{await navigator.share({title:'Mohit Gaming Portfolio',text:'Check my gaming website!',url})}catch(e){}}else{await navigator.clipboard.writeText(url);alert('Website link copied!')}}
$('#challengeForm').onsubmit=e=>{e.preventDefault();let x={name:$('#challengerName').value,game:$('#challengerGame').value,uid:$('#challengerUid').value,user:$('#challengerUsername').value,ig:$('#challengerInstagram').value,msg:$('#challengeMsg').value};S.challenges=S.challenges||[];S.challenges.unshift(x);save();e.target.reset();alert('Challenge saved on this browser!')};
$('#contactForm').onsubmit=e=>{if(!S.email){e.preventDefault();alert('Settings में FormSubmit Email डालें।')}else{e.target.action='https://formsubmit.co/'+encodeURIComponent(S.email);e.target.method='POST';}};
$('#editAboutBtn').onclick=()=>{$('#settings').classList.add('open');$('#aboutInput').focus()};$('#reset').onclick=()=>{if(confirm('Reset all local edits?')){localStorage.removeItem(KEY);location.reload()}};setForm();apply();renderW();renderH();
