const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
window.addEventListener("load",()=>setTimeout(()=>$("#loader").style.display="none",700));
const saved=localStorage.getItem("mohit-theme"); if(saved==="light")document.body.classList.add("light");
$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("mohit-theme",document.body.classList.contains("light")?"light":"dark");$("#themeBtn").textContent=document.body.classList.contains("light")?"🌙":"☀️"};
$("#langBtn").onclick=()=>{const hi=document.documentElement.lang!=="hi";document.documentElement.lang=hi?"hi":"en";$("#langBtn").textContent=hi?"English":"हिंदी";$$("[data-en]").forEach(e=>e.textContent=hi?e.dataset.hi:e.dataset.en);localStorage.setItem("mohit-lang",hi?"hi":"en")};
if(localStorage.getItem("mohit-lang")==="hi")$("#langBtn").click();
$("#menuBtn").onclick=()=>$("#navLinks").classList.toggle("open"); $$("#navLinks a").forEach(a=>a.onclick=()=>$("#navLinks").classList.remove("open"));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("show")}),{threshold:.12}); $$(".reveal").forEach(e=>observer.observe(e));
document.addEventListener("mousemove",e=>{$(".cursor-glow").style.left=e.clientX+"px";$(".cursor-glow").style.top=e.clientY+"px"});
$$(".tilt").forEach(c=>c.addEventListener("mousemove",e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(700px) rotateY(${x*8}deg) rotateX(${-y*8}deg)`;c.addEventListener("mouseleave",()=>c.style.transform="")}));
function clock(){const d=new Date();$("#liveTime").textContent=d.toLocaleTimeString();$("#liveDate").textContent=d.toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"});const h=d.getHours();$("#greeting").textContent=(h<12?"Good Morning":h<17?"Good Afternoon":h<21?"Good Evening":"Good Night")+" 👋";} clock();setInterval(clock,1000);
async function weather(){try{let lat=26.9124,lon=75.7873,name="Jaipur";if(navigator.geolocation){try{const p=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:3500}));lat=p.coords.latitude;lon=p.coords.longitude;name="Your Location"}catch(e){}}const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,wind_speed_10m,weather_code`;const d=await fetch(u).then(r=>r.json()),c=d.current;$("#weatherPlace").textContent=name;$("#temp").textContent=Math.round(c.temperature_2m)+"°C";$("#humidity").textContent=Math.round(c.relative_humidity_2m)+"%";$("#wind").textContent=Math.round(c.wind_speed_10m)+" km/h";$("#feels").textContent=Math.round(c.apparent_temperature)+"°C";const codes={0:["☀️","Clear"],1:["🌤️","Mostly Clear"],2:["⛅","Partly Cloudy"],3:["☁️","Cloudy"],45:["🌫️","Fog"],48:["🌫️","Fog"],51:["🌦️","Drizzle"],61:["🌧️","Rain"],71:["🌨️","Snow"],80:["🌦️","Showers"],95:["⛈️","Thunderstorm"]};const x=codes[c.weather_code]||["🌤️","Nice Weather"];$("#weatherIcon").textContent=x[0];$("#weatherText").textContent=x[1]}catch(e){$("#weatherText").textContent="Weather unavailable right now"}} weather();$("#weatherBtn").onclick=weather;
window.addEventListener("scroll",()=>{$("#topBtn").style.display=scrollY>500?"block":"none";$(".nav").classList.toggle("scrolled",scrollY>20)});$("#topBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"});
// Premium gallery interactions
const modal=document.getElementById("galleryModal"), modalImg=document.getElementById("modalImg"), modalTitle=document.getElementById("modalTitle"), modalDesc=document.getElementById("modalDesc");
document.querySelectorAll(".pro-card").forEach(card=>{card.querySelector(".view-btn").addEventListener("click",e=>{e.preventDefault(); const img=card.querySelector("img"); modalImg.src=img.src; modalImg.alt=img.alt; modalTitle.textContent=card.dataset.title; modalDesc.textContent=card.dataset.desc; modal.classList.add("open"); modal.setAttribute("aria-hidden","false")})});
function closeGallery(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
document.getElementById("modalClose").onclick=closeGallery; modal.addEventListener("click",e=>{if(e.target===modal)closeGallery()}); document.addEventListener("keydown",e=>{if(e.key==="Escape")closeGallery()});
const musicBtn=document.getElementById("musicBtn"); if(musicBtn) musicBtn.onclick=()=>{musicBtn.textContent=musicBtn.textContent==="♫"?"🔇":"♫"};
