const KEY='mohit_editable_v1';let S=JSON.parse(localStorage.getItem(KEY)||'{}');
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function apply(){
 document.body.className=(S.theme?'theme-'+S.theme:'')+' '+(S.anim&&S.anim!=='none'?'gallery-anim-'+S.anim:'')+' no-zoom '+(S.light?'light-mode ':'')+(S.motion==='on'?'reduce-motion':'');
 document.querySelectorAll('[data-name]').forEach(e=>e.textContent=S.name||'Mohit');
 document.querySelectorAll('[data-tagline]').forEach(e=>e.textContent=S.tagline||'Gamer • Creator • Student • 5x_gamerr');
 if(S.photo){$('#profilePhoto').src=S.photo;$('#navPhoto').src=S.photo;document.querySelectorAll('.mini-profile').forEach(e=>e.src=S.photo)}
 $('#aboutText').textContent=S.about||'Welcome to my personal gaming portfolio. Explore my gaming world, gallery, challenges and history.';
 $('#gamingNameText').textContent=(S.gamingName||S.name||'Mohit')+' • '+(S.gamingUser||'5x_gamerr');$('#gamingGameText').textContent=S.gamingGame||'FREE FIRE';$('#gamingUidText').textContent=S.uid?('UID: '+S.uid):'UID not set';$('#gamingIgText').textContent=S.gamingIg||'@5x_gamerr';$('#gamingContactText').textContent=S.gamingContact||'Not set';$('#statusText').textContent=S.status||'ONLINE';
 document.body.classList.toggle('cursor-off',S.cursor==='off');
 $('#particles').style.display=S.particles==='off'?'none':'block';
}
function typeTagline(){const el=$('[data-tagline]');if(!el)return;const text=S.tagline||'Gamer • Creator • Student • 5x_gamerr';if(S.typing==='off'){el.textContent=text;return}let i=0;el.textContent='';clearInterval(window.__typing);window.__typing=setInterval(()=>{el.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(window.__typing)},45)}
window.addEventListener('load',()=>{if(S.loader==='off')$('#loader').style.display='none';else setTimeout(()=>$('#loader').style.display='none',650);setTimeout(typeTagline,700)});
$('#settingsBtn').onclick=()=>$('#settings').classList.add('open');$('.close').onclick=()=>$('#settings').classList.remove('open');$('.backdrop').onclick=()=>$('#settings').classList.remove('open');
$('#themeBtn').onclick=()=>{S.light=!S.light;save();apply()};
$('#themeSelect').onchange=e=>{S.theme=e.target.value;save();apply()};$('#animSelect').onchange=e=>{S.anim=e.target.value;save();apply()};
$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;if(f.size>4e6)return alert('Photo 4MB से कम रखें');let r=new FileReader();r.onload=()=>{S.photo=r.result;save();apply()};r.readAsDataURL(f)};
$('#songInput').onchange=e=>{let f=e.target.files[0];if(!f)return;if(f.size>12e6)return alert('Song 12MB से कम रखें');let r=new FileReader();r.onload=()=>{S.song=r.result;$('#audio').src=S.song;save()};r.readAsDataURL(f)};$('#songPlay').onclick=()=>$('#audio').paused?$('#audio').play():$('#audio').pause();
$('#saveProfile').onclick=()=>{S.name=$('#nameInput').value.trim();S.tagline=$('#tagInput').value.trim();S.about=$('#aboutInput').value.trim();S.email=$('#formEmail').value.trim();save();apply();setForm();typeTagline();alert('Profile settings saved!')};
function setForm(){if(S.email)$('#formEmail').value=S.email;$('#nameInput').value=S.name||'';$('#tagInput').value=S.tagline||'';$('#aboutInput').value=S.about||'';if(S.song)$('#audio').src=S.song;$('#themeSelect').value=S.theme||'cyan';$('#animSelect').value=S.anim||'none';$('#gamingNameInput').value=S.gamingName||S.name||'';$('#gamingUserInput').value=S.gamingUser||'5x_gamerr';$('#gamingGameInput').value=S.gamingGame||'FREE FIRE';$('#uidInput').value=S.uid||'';$('#gamingIgInput').value=S.gamingIg||'@5x_gamerr';$('#gamingContactInput').value=S.gamingContact||'';$('#statusInput').value=S.status||'ONLINE';$('#particlesSelect').value=S.particles||'on';$('#cursorSelect').value=S.cursor||'on';$('#typingSelect').value=S.typing||'on';$('#loaderSelect').value=S.loader||'on';$('#motionSelect').value=S.motion||'off'}
$('#saveExtras').onclick=()=>{S.gamingName=$('#gamingNameInput').value.trim();S.gamingUser=$('#gamingUserInput').value.trim();S.gamingGame=$('#gamingGameInput').value.trim();S.uid=$('#uidInput').value.trim();S.gamingIg=$('#gamingIgInput').value.trim();S.gamingContact=$('#gamingContactInput').value.trim();S.status=$('#statusInput').value.trim()||'ONLINE';S.particles=$('#particlesSelect').value;S.cursor=$('#cursorSelect').value;S.typing=$('#typingSelect').value;S.loader=$('#loaderSelect').value;S.motion=$('#motionSelect').value;save();apply();typeTagline();alert('Extra gaming options saved!')};
function renderW(){let a=S.winners||[];$('#winnerGrid').innerHTML=a.map((x,i)=>`<article class="winner-card"><img src="${x.img}" alt="Winner shot"><b>${esc(x.cap)}</b><br><button onclick="delW(${i})">Delete</button></article>`).join('')||'<p class="muted">No winner shots yet. Add them from Settings.</p>'}window.delW=i=>{S.winners.splice(i,1);save();renderW()};
$('#addWinner').onclick=()=>{let f=$('#winnerInput').files[0],c=$('#winnerCaption').value.trim();if(!f||!c)return alert('Screenshot और caption डालें');if(f.size>4e6)return alert('Winner image 4MB से कम रखें');let r=new FileReader();r.onload=()=>{S.winners=S.winners||[];S.winners.unshift({img:r.result,cap:c});save();renderW();$('#winnerInput').value='';$('#winnerCaption').value=''};r.readAsDataURL(f)};
function renderH(){let a=S.history||[];$('#historyGrid').innerHTML=a.map((x,i)=>`<article class="history-card"><b>${esc(x.game)}</b><p>UID: ${esc(x.uid)}</p><p>Username: ${esc(x.user)}</p><button onclick="delH(${i})">Delete</button></article>`).join('')||'<p class="muted">No gaming history yet.</p>'}window.delH=i=>{S.history.splice(i,1);save();renderH()};
$('#addHistory').onclick=()=>{let game=$('#histGame').value.trim(),uid=$('#histUid').value.trim(),user=$('#histUser').value.trim();if(!game||!uid||!user)return alert('Game, UID और Username भरें');S.history=S.history||[];S.history.unshift({game,uid,user});save();renderH();$('#histGame').value=$('#histUid').value=$('#histUser').value=''};
$('#shareBtn').onclick=()=>share();$('#shareSettings').onclick=()=>share();async function share(){let url='https://mohitbishnoi7568-alt.github.io/';if(navigator.share){try{await navigator.share({title:'Mohit Gaming Portfolio',text:'Check my gaming website!',url})}catch(e){}}else{try{await navigator.clipboard.writeText(url);alert('Website link copied!')}catch(e){prompt('Copy website link:',url)}}}
$('#challengeForm').onsubmit=e=>{if(!S.email){e.preventDefault();alert('Settings में FormSubmit Email डालें।');return}e.target.action='https://formsubmit.co/'+encodeURIComponent(S.email);e.target.method='POST';e.target.enctype='application/x-www-form-urlencoded';e.target.querySelectorAll('input[data-auto]').forEach(x=>x.remove());const add=(name,value)=>{let x=document.createElement('input');x.type='hidden';x.name=name;x.value=value;x.dataset.auto='1';e.target.appendChild(x)};add('_next',new URL('thank-you.html',location.href).href);add('_subject','New Gaming Profile Details - 5x_gamerr');add('_captcha','false');};
$('#contactForm').onsubmit=e=>{if(!S.email){e.preventDefault();alert('Settings में FormSubmit Email डालें।')}else{e.target.action='https://formsubmit.co/'+encodeURIComponent(S.email);e.target.method='POST'}};
$('#editAboutBtn').onclick=()=>{$('#settings').classList.add('open');$('#aboutInput').focus()};$('#reset').onclick=()=>{if(confirm('Reset all local edits?')){localStorage.removeItem(KEY);location.reload()}};
// lightweight particle background
const pc=$('#particles'),ctx=pc.getContext('2d');let pts=[];function resize(){pc.width=innerWidth;pc.height=innerHeight;pts=Array.from({length:Math.min(65,Math.floor(innerWidth/18))},()=>({x:Math.random()*pc.width,y:Math.random()*pc.height,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.5+.4}))}function draw(){if(S.particles==='off'){requestAnimationFrame(draw);return}ctx.clearRect(0,0,pc.width,pc.height);ctx.fillStyle='rgba(0,234,255,.65)';for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>pc.width)p.vx*=-1;if(p.y<0||p.y>pc.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
// subtle cursor glow on desktop
addEventListener('pointermove',e=>{const g=$('#cursorGlow');if(S.cursor==='off'||innerWidth<700){g.style.opacity=0;return}g.style.opacity=1;g.style.transform=`translate(${e.clientX-90}px,${e.clientY-90}px)`});
setForm();apply();renderW();renderH();
